Repository EzarDev/eZaR, pull requests merged in 2022-06, with the labels that each got.

#3 Haha yes uh license go brrr :)
  LICENSE
  ezar/__init__.py
  ezar/backend/config/__init__.py
  ezar/utils/ezar.py
Labels: p: Medium, t: bug

#4 feat: use docker with compose
  Dockerfile
  docker-compose.yml
Labels: p: Medium, t: feature

#5 feat: add README.md file
  README.md
Labels: t: documentation, p: Low

#7 chore(pre-commit): update config file
  ezar/utils/__init__.py
  ezar/utils/embed.py
Labels: p: Low, t: bug
